// ==================================================
// HR Project — Core TypeScript Types
// ==================================================
// Central type definitions shared across the entire application.
// Database-specific types live in database.ts (auto-generated by Supabase CLI).
// ==================================================

// --------------------------------------------------
// ENUMS
// --------------------------------------------------

export type UserRole = "super_admin" | "admin" | "recruiter" | "viewer";

export type JobStatus = "draft" | "active" | "paused" | "closed" | "archived";

export type CandidateStatus =
  | "new"
  | "screening"
  | "whatsapp_interview"
  | "assignment_sent"
  | "assignment_submitted"
  | "under_review"
  | "shortlisted"
  | "rejected"
  | "hired"
  | "withdrawn";

export type WhatsAppProvider = "twilio" | "meta";

export type AIProvider = "anthropic" | "openai" | "gemini" | "ollama" | "openrouter";

export type MessageDirection = "inbound" | "outbound";

export type MessageSender = "candidate" | "ai" | "recruiter";

export type AssignmentStatus = "pending" | "sent" | "submitted" | "evaluated" | "expired";

// --------------------------------------------------
// ORGANIZATION
// --------------------------------------------------

export interface Organization {
  id: string;
  name: string;
  slug: string;
  logo_url?: string;
  created_at: string;
  updated_at: string;
}

// --------------------------------------------------
// USER / RECRUITER
// --------------------------------------------------

export interface RecruiterProfile {
  id: string;
  organization_id: string;
  email: string;
  full_name: string;
  avatar_url?: string;
  role: UserRole;
  created_at: string;
}

// --------------------------------------------------
// JOB
// --------------------------------------------------

export interface Job {
  id: string;
  organization_id: string;
  created_by: string;
  title: string;
  description: string;
  requirements: string[];
  culture_fit_expectations?: string;
  status: JobStatus;
  slug: string;
  department?: string;
  location?: string;
  employment_type?: "full_time" | "part_time" | "contract" | "internship";
  salary_range?: { min: number; max: number; currency: string };
  screening_questions: ScreeningQuestion[];
  rejection_rules: RejectionRule[];
  ai_instructions?: string;
  created_at: string;
  updated_at: string;
}

export interface ScreeningQuestion {
  id: string;
  question: string;
  type: "open" | "yes_no" | "multiple_choice" | "numeric";
  options?: string[];
  required: boolean;
  weight: number; // 1–10, used in scoring
}

export interface RejectionRule {
  id: string;
  field: string;
  operator: "equals" | "not_equals" | "contains" | "less_than" | "greater_than";
  value: string | number | boolean;
  reason: string;
}

// --------------------------------------------------
// CANDIDATE
// --------------------------------------------------

export interface Candidate {
  id: string;
  job_id: string;
  organization_id: string;
  full_name: string;
  email: string;
  phone: string; // E.164 format: +972501234567
  whatsapp_number?: string;
  cv_url?: string;
  cv_parsed_data?: CVParsedData;
  status: CandidateStatus;
  ai_score?: number; // 0–100
  ai_summary?: string;
  recruiter_notes?: string;
  is_ai_active: boolean; // false = recruiter has taken over
  applied_at: string;
  updated_at: string;
}

export interface CVParsedData {
  skills: string[];
  experience_years?: number;
  education?: string[];
  previous_roles?: string[];
  languages?: string[];
  raw_text?: string;
}

// --------------------------------------------------
// WHATSAPP / MESSAGES
// --------------------------------------------------

export interface WhatsAppMessage {
  id: string;
  candidate_id: string;
  direction: MessageDirection;
  sender: MessageSender;
  content: string;
  media_url?: string;
  whatsapp_message_id?: string;
  sent_at: string;
}

export interface ConversationContext {
  candidate_id: string;
  job_id: string;
  messages: WhatsAppMessage[];
  current_question_index: number;
  is_complete: boolean;
  metadata: Record<string, unknown>;
}

// --------------------------------------------------
// ASSIGNMENT
// --------------------------------------------------

export interface Assignment {
  id: string;
  job_id: string;
  candidate_id: string;
  title: string;
  description: string;
  instructions: string;
  deadline_hours: number;
  status: AssignmentStatus;
  submission_url?: string;
  submission_text?: string;
  ai_evaluation?: AssignmentEvaluation;
  sent_at?: string;
  submitted_at?: string;
  created_at: string;
}

export interface AssignmentEvaluation {
  score: number; // 0–100
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendation: "proceed" | "reject" | "borderline";
  evaluated_at: string;
}

// --------------------------------------------------
// AI LAYER
// --------------------------------------------------

export interface AIMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export interface AIRequestOptions {
  provider?: AIProvider;
  model?: string;
  maxTokens?: number;
  temperature?: number;
  systemPrompt?: string;
}

export interface AIResponse {
  content: string;
  provider: AIProvider;
  model: string;
  usage: {
    input_tokens: number;
    output_tokens: number;
  };
}

// --------------------------------------------------
// API RESPONSES
// --------------------------------------------------

export interface ApiSuccess<T = unknown> {
  success: true;
  data: T;
}

export interface ApiError {
  success: false;
  error: string;
  code?: string;
}

export type ApiResponse<T = unknown> = ApiSuccess<T> | ApiError;

// --------------------------------------------------
// PAGINATION
// --------------------------------------------------

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}
